### ISSUE TITLE
Elo.cs does not compile

### ISSUE THREAD

**Issue by aarondemarre** [FigBug/Multiplayer-ELO#1]
Elo.cs does not compile using .NET 4.5.

On line 53 this:
int n = players.Count();

Should be:
int n = players.Count;

List<T>.Count is a property of the list, whereas List<T>.Count() is an extension method from Linq, which is not referenced.

Thanks for the code, saved me from doing the math!

**Comment by FigBug** [comment]
Fixed. It worked fine in the online C# compiler I used. I'm not really a C# programmer.
